server:
  port: 6636
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project2
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 86400
  refreshable-duration: 2592000

# ✅ Bật log chi tiết để debug Spring Security
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.hibernate.SQL: DEBUG           # Log câu SQL
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Log binding parameter SQL
    org.springframework.boot.web.servlet.FilterRegistrationBean: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
