server:
  servlet:
    context-path: /api/v1
  port: 5454

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project2
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  signerKey: '1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij'
  valid-duration: 86400
  refreshable-duration: 2592000